// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFryHlMHWkw30GRy6GTLvSoJJalXb_nc4',
    appId: '1:478491100495:android:6f0ea774d5c0ebd4a0b13a',
    messagingSenderId: '478491100495',
    projectId: 'riyadh-transportation-re-a7e4b',
    databaseURL: 'https://riyadh-transportation-re-a7e4b-default-rtdb.firebaseio.com',
    storageBucket: 'riyadh-transportation-re-a7e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLEl7H5zTpGAV1F5BOkgBjF8gB6bwzNc8',
    appId: '1:478491100495:ios:9a7d846f59715dbea0b13a',
    messagingSenderId: '478491100495',
    projectId: 'riyadh-transportation-re-a7e4b',
    databaseURL: 'https://riyadh-transportation-re-a7e4b-default-rtdb.firebaseio.com',
    storageBucket: 'riyadh-transportation-re-a7e4b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );
}
